apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rag-service
  labels:
    app.kubernetes.io/name: rag-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8004
      targetPort: 8004
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: rag-service
    app.kubernetes.io/instance: {{ .Release.Name }}
