{{- if and (eq (default "kafka" .Values.stream.backend) "redis") (ne .Values.redis.managed false) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: event-stream
spec:
  {{- if .Values.redis.storageClassName }}
  storageClassName: {{ .Values.redis.storageClassName | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storageSize }}
{{- end }}
