apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-api-gateway
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
