apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sms-gateway
  labels:
    app.kubernetes.io/name: sms-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: sms-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
