apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lil-evy-node-manager-default-deny
  namespace: lil-evy-fleet
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: lil-evy-node-manager
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: lil-evy-fleet
      ports:
        - protocol: TCP
          port: 8006
