apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: big-evy-corpus-factory
resources:
  - namespace.yaml
  - ../../base
  - egressfirewall.yaml
images:
  - name: quay.io/rh-ai-quickstart/corpus-acquisition-controller
    newTag: latest
