upstream edge_nodes {
    server node-1-gateway:8000;
    server node-2-gateway:8000;
    server node-3-gateway:8000;
}

server {
    listen 8000;

    location / {
        proxy_pass http://edge_nodes;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
